#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
set -euo pipefail

cd "$SCRIPT_DIR"

function log() {
    echo "$1" > /dev/stderr
}

function fail() {
    log "$1"
    exit 1
}

function find_free_nbd_device() {
    for INDEX in $(seq 0 15); do
        if ! test -e /sys/class/block/nbd"$INDEX"/pid; then
            echo "$INDEX"
            return
        fi
    done

    fail "No /dev/nbd device available!"
}

if test "$(id -u)" -ne 0; then
    fail "Run this command as root"
fi

if ! test -e /dev/nbd0; then
    log ""
    modprobe nbd
fi

NBD_DEVICE="/dev/nbd$(find_free_nbd_device)"
log "Exposing image.qcow2 to $NBD_DEVICE"
qemu-nbd --connect "$NBD_DEVICE" -f qcow2 "image.qcow2"

log "Waiting for partitions to be recognized"
sleep 1

ls "$NBD_DEVICE"p*

for PARTITION in "$NBD_DEVICE"p*; do
    SUFFIX=$(echo "$PARTITION" | sed 's|'"$NBD_DEVICE"'||')
    mkdir -p "$SUFFIX"
    log "Mounting read-only $PARTITION to $SUFFIX"
    if ! mount -o ro "$PARTITION" "$SUFFIX" >& /dev/null; then
        log "Couldn't mount $PARTITION: $(file -s "$PARTITION")"
    fi
done

log "Press any key to unmount"
read

qemu-nbd --disconnect "$NBD_DEVICE" >& /dev/null

for PARTITION in "$NBD_DEVICE"p*; do
    SUFFIX=$(echo "$PARTITION" | sed 's|'"$NBD_DEVICE"'||')
    log "Removing $SUFFIX"
    if mountpoint "$SUFFIX" >& /dev/null; then
        umount "$SUFFIX"
    fi
    rmdir "$SUFFIX"
done

log "All done"
